from typing import Dict, List
from models.schemas import (
    Person, AppearanceSnapshot, MovementEvent, Camera, 
    RoomZone, SecurityAlert, SecurityRule, PersonRole, 
    AccessStatus, AlertSeverity, AlertType, AlertStatus
)

INITIAL_PERSONS: Dict[str, Person] = {
    "P-10087": Person(
        id="p1",
        person_id="P-10087",
        track_id="TRK-25-000567",
        name="Rahul Sharma",
        mobile="9876543210",
        email="rahul.sharma@email.com",
        id_proof_type="Aadhaar Card",
        id_proof_number="1234 5678 9012",
        role=PersonRole.VISITOR,
        permission_type="Temporary",
        valid_from="2025-08-24 10:00 AM",
        valid_to="2025-08-24 06:00 PM",
        allowed_zones=["Floor 1 - Reception", "Floor 2 - Meeting Room", "Floor 2 - Office 201", "Floor 2 - Corridor"],
        photo_url="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face",
        today_appearance_url="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
        status=AccessStatus.AUTHORIZED,
        notes="Meeting with Marketing & AI Analytics Team",
        current_building="Corporate Tower A",
        current_floor="Floor 2",
        current_room="Meeting Room",
        current_camera_id="CAM-021",
        last_seen_time="10:24:32 AM",
        x_pos=68.5,
        y_pos=42.0
    ),
    "P-00182": Person(
        id="p2",
        person_id="P-00182",
        track_id="TRK-2025-000089",
        name="Amit Kumar",
        mobile="9811223344",
        email="amit.kumar@corp.com",
        id_proof_type="Passport",
        id_proof_number="Z8942110",
        role=PersonRole.EMPLOYEE,
        permission_type="Permanent",
        valid_from="2024-01-01 00:00 AM",
        valid_to="2027-12-31 11:59 PM",
        allowed_zones=["Floor 1", "Floor 2", "Floor 3", "Floor 4 - Server Hub"],
        photo_url="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
        today_appearance_url="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
        status=AccessStatus.AUTHORIZED,
        notes="Lead Systems Architect",
        current_building="Corporate Tower A",
        current_floor="Floor 2",
        current_room="Server Room",
        current_camera_id="CAM-019",
        last_seen_time="10:25:01 AM",
        x_pos=18.0,
        y_pos=72.0
    ),
    "P-00214": Person(
        id="p3",
        person_id="P-00214",
        track_id="TRK-2025-000104",
        name="Priya Singh",
        mobile="9877665544",
        email="priya.singh@corp.com",
        id_proof_type="National ID",
        id_proof_number="ID-994821",
        role=PersonRole.EMPLOYEE,
        permission_type="Permanent",
        valid_from="2024-03-01 00:00 AM",
        valid_to="2027-12-31 11:59 PM",
        allowed_zones=["Floor 1", "Floor 2", "Floor 3"],
        photo_url="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&crop=face",
        today_appearance_url="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&crop=face",
        status=AccessStatus.AUTHORIZED,
        notes="Product Operations Manager",
        current_building="Corporate Tower A",
        current_floor="Floor 2",
        current_room="Office 201",
        current_camera_id="CAM-018",
        last_seen_time="10:24:15 AM",
        x_pos=22.0,
        y_pos=28.0
    ),
    "P-00305": Person(
        id="p4",
        person_id="P-00305",
        track_id="TRK-2025-000155",
        name="Vikram Patel",
        mobile="9899887766",
        email="vikram.patel@corp.com",
        id_proof_type="Aadhaar Card",
        id_proof_number="8832 9912 0019",
        role=PersonRole.SECURITY,
        permission_type="Permanent",
        valid_from="2024-01-01 00:00 AM",
        valid_to="2028-12-31 11:59 PM",
        allowed_zones=["Floor 1", "Floor 2", "Floor 3", "Floor 4"],
        photo_url="https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=face",
        today_appearance_url="https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=face",
        status=AccessStatus.AUTHORIZED,
        notes="Head of Physical Security",
        current_building="Corporate Tower A",
        current_floor="Floor 2",
        current_room="Elevator Lobby",
        current_camera_id="CAM-015",
        last_seen_time="10:25:12 AM",
        x_pos=64.0,
        y_pos=78.0
    ),
    "P-UNKNOWN-1": Person(
        id="p5",
        person_id="P-UNKNOWN-1",
        track_id="TRK-2025-000941",
        name="Unknown Individual #941",
        mobile="Unregistered",
        email="unregistered@domain",
        id_proof_type="None",
        id_proof_number="N/A",
        role=PersonRole.VISITOR,
        permission_type="None",
        valid_from="N/A",
        valid_to="N/A",
        allowed_zones=[],
        photo_url="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face",
        today_appearance_url="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face",
        status=AccessStatus.ALERT,
        notes="Breached Server Room without authorization",
        current_building="Corporate Tower A",
        current_floor="Floor 2",
        current_room="Server Room",
        current_camera_id="CAM-019",
        last_seen_time="10:24:55 AM",
        x_pos=26.0,
        y_pos=76.0
    )
}

INITIAL_APPEARANCES: Dict[str, List[AppearanceSnapshot]] = {
    "P-10087": [
        AppearanceSnapshot(
            id="app-1",
            person_id="P-10087",
            date="24 Aug 2025",
            time="09:47 AM",
            photo_url="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
            outfit_description="Navy Blue Oxford Shirt with silver watch",
            is_today=True
        ),
        AppearanceSnapshot(
            id="app-2",
            person_id="P-10087",
            date="23 Aug 2025",
            time="09:38 AM",
            photo_url="https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&h=300&fit=crop&crop=face",
            outfit_description="Red Plaid Button-Down Shirt",
            is_today=False
        ),
        AppearanceSnapshot(
            id="app-3",
            person_id="P-10087",
            date="22 Aug 2025",
            time="09:41 AM",
            photo_url="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop&crop=face",
            outfit_description="Charcoal Gray Crew Neck",
            is_today=False
        ),
        AppearanceSnapshot(
            id="app-4",
            person_id="P-10087",
            date="21 Aug 2025",
            time="09:35 AM",
            photo_url="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop&crop=face",
            outfit_description="Mustard Yellow Casual Shirt",
            is_today=False
        ),
        AppearanceSnapshot(
            id="app-5",
            person_id="P-10087",
            date="20 Aug 2025",
            time="09:40 AM",
            photo_url="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face",
            outfit_description="Classic Black Formal Suit",
            is_today=False
        )
    ]
}

INITIAL_TIMELINES: Dict[str, List[MovementEvent]] = {
    "P-10087": [
        MovementEvent(
            id="m1",
            person_id="P-10087",
            track_id="TRK-25-000567",
            timestamp="09:42:11 AM",
            camera_id="CAM-001",
            building="Corporate Tower A",
            floor="Floor 1",
            room="Main Entrance",
            event_type="ENTER",
            dwell_time_seconds=51
        ),
        MovementEvent(
            id="m2",
            person_id="P-10087",
            track_id="TRK-25-000567",
            timestamp="09:43:02 AM",
            camera_id="CAM-003",
            building="Corporate Tower A",
            floor="Floor 1",
            room="Reception",
            event_type="ENROLLED",
            dwell_time_seconds=135
        ),
        MovementEvent(
            id="m3",
            person_id="P-10087",
            track_id="TRK-25-000567",
            timestamp="09:45:17 AM",
            camera_id="CAM-007",
            building="Corporate Tower A",
            floor="Floor 1",
            room="Elevator Lobby",
            event_type="TRANSIT",
            dwell_time_seconds=45
        ),
        MovementEvent(
            id="m4",
            person_id="P-10087",
            track_id="TRK-25-000567",
            timestamp="09:46:02 AM",
            camera_id="CAM-014",
            building="Corporate Tower A",
            floor="Floor 2",
            room="Corridor",
            event_type="TRANSIT",
            dwell_time_seconds=122
        ),
        MovementEvent(
            id="m5",
            person_id="P-10087",
            track_id="TRK-25-000567",
            timestamp="09:48:04 AM",
            camera_id="CAM-018",
            building="Corporate Tower A",
            floor="Floor 2",
            room="Office 201",
            event_type="ENTER",
            dwell_time_seconds=2047
        ),
        MovementEvent(
            id="m6",
            person_id="P-10087",
            track_id="TRK-25-000567",
            timestamp="10:22:11 AM",
            camera_id="CAM-021",
            building="Corporate Tower A",
            floor="Floor 2",
            room="Meeting Room",
            event_type="CURRENT",
            dwell_time_seconds=150
        )
    ]
}

INITIAL_ROOMS_FLOOR2: List[RoomZone] = [
    RoomZone(
        id="room-201",
        name="Office 201",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=10,
        current_occupancy=4,
        is_restricted=False,
        allowed_roles=["Employee", "Visitor", "VIP"],
        occupants=["P-00214"],
        x=5.0,
        y=5.0,
        width=38.0,
        height=38.0
    ),
    RoomZone(
        id="room-202",
        name="Office 202",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=8,
        current_occupancy=2,
        is_restricted=False,
        allowed_roles=["Employee", "Visitor"],
        occupants=[],
        x=57.0,
        y=5.0,
        width=38.0,
        height=28.0
    ),
    RoomZone(
        id="room-meeting",
        name="Meeting Room",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=16,
        current_occupancy=8,
        is_restricted=False,
        allowed_roles=["Employee", "Visitor", "VIP"],
        occupants=["P-10087"],
        x=57.0,
        y=35.0,
        width=38.0,
        height=32.0
    ),
    RoomZone(
        id="room-server",
        name="Server Room",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=4,
        current_occupancy=3,
        is_restricted=True,
        allowed_roles=["Security", "Employee"],
        occupants=["P-00182", "P-UNKNOWN-1"],
        x=5.0,
        y=58.0,
        width=38.0,
        height=37.0
    ),
    RoomZone(
        id="room-corridor",
        name="Corridor",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=50,
        current_occupancy=7,
        is_restricted=False,
        allowed_roles=["Employee", "Visitor", "Security"],
        occupants=[],
        x=44.0,
        y=5.0,
        width=12.0,
        height=90.0
    ),
    RoomZone(
        id="room-lift",
        name="Lift Lobby",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=20,
        current_occupancy=2,
        is_restricted=False,
        allowed_roles=["Employee", "Visitor", "Security"],
        occupants=["P-00305"],
        x=57.0,
        y=69.0,
        width=22.0,
        height=26.0
    ),
    RoomZone(
        id="room-pantry",
        name="Pantry",
        building="Corporate Tower A",
        floor="Floor 2",
        max_capacity=10,
        current_occupancy=1,
        is_restricted=False,
        allowed_roles=["Employee", "Visitor"],
        occupants=[],
        x=80.0,
        y=69.0,
        width=15.0,
        height=26.0
    )
]

INITIAL_CAMERAS: List[Camera] = [
    Camera(
        id="cam-1",
        camera_id="CAM-001",
        name="Main Entrance Gate 1",
        building="Corporate Tower A",
        floor="Floor 1",
        room="Main Entrance",
        status="Online",
        fps=30,
        resolution="4K UHD (3840x2160)",
        latency_ms=16,
        ai_models=["YOLOv8x", "DeepFace", "ByteTrack"],
        fov_angle=110,
        x_pos=50.0,
        y_pos=95.0
    ),
    Camera(
        id="cam-3",
        camera_id="CAM-003",
        name="Reception Desk & Turnstile",
        building="Corporate Tower A",
        floor="Floor 1",
        room="Reception",
        status="Online",
        fps=30,
        resolution="4K UHD (3840x2160)",
        latency_ms=18,
        ai_models=["YOLOv8x", "FaceNet", "Re-ID"],
        fov_angle=90,
        x_pos=30.0,
        y_pos=60.0
    ),
    Camera(
        id="cam-14",
        camera_id="CAM-014",
        name="Floor 2 North Corridor",
        building="Corporate Tower A",
        floor="Floor 2",
        room="Corridor",
        status="Online",
        fps=30,
        resolution="1080p Full HD",
        latency_ms=14,
        ai_models=["YOLOv8n", "ByteTrack"],
        fov_angle=90,
        x_pos=50.0,
        y_pos=30.0
    ),
    Camera(
        id="cam-18",
        camera_id="CAM-018",
        name="Office 201 Internal",
        building="Corporate Tower A",
        floor="Floor 2",
        room="Office 201",
        status="Online",
        fps=25,
        resolution="1080p Full HD",
        latency_ms=19,
        ai_models=["YOLOv8n", "DeepFace"],
        fov_angle=85,
        x_pos=38.0,
        y_pos=8.0
    ),
    Camera(
        id="cam-19",
        camera_id="CAM-019",
        name="Server Room Restricted Vault",
        building="Corporate Tower A",
        floor="Floor 2",
        room="Server Room",
        status="Online",
        fps=30,
        resolution="4K UHD (3840x2160)",
        latency_ms=15,
        ai_models=["YOLOv8x", "DeepFace", "AnomalyNet"],
        fov_angle=120,
        x_pos=8.0,
        y_pos=60.0
    ),
    Camera(
        id="cam-21",
        camera_id="CAM-021",
        name="Executive Meeting Room A",
        building="Corporate Tower A",
        floor="Floor 2",
        room="Meeting Room",
        status="Online",
        fps=30,
        resolution="4K UHD (3840x2160)",
        latency_ms=17,
        ai_models=["YOLOv8x", "DeepFace"],
        fov_angle=90,
        x_pos=92.0,
        y_pos=38.0
    ),
    Camera(
        id="cam-15",
        camera_id="CAM-015",
        name="Floor 2 Elevator Lobby",
        building="Corporate Tower A",
        floor="Floor 2",
        room="Lift Lobby",
        status="Online",
        fps=30,
        resolution="1080p Full HD",
        latency_ms=16,
        ai_models=["YOLOv8n", "ByteTrack"],
        fov_angle=90,
        x_pos=59.0,
        y_pos=92.0
    )
]

INITIAL_ALERTS: List[SecurityAlert] = [
    SecurityAlert(
        id="alt-101",
        alert_id="ALT-2025-0824-001",
        timestamp="10:24 AM",
        severity=AlertSeverity.CRITICAL,
        type=AlertType.UNAUTHORIZED_ACCESS,
        title="Unauthorized Access - Server Room",
        description="Unregistered person TRK-2025-000941 detected inside restricted Server Room without clearance.",
        building="Corporate Tower A",
        floor="Floor 2",
        room="Server Room",
        camera_id="CAM-019",
        person_id="P-UNKNOWN-1",
        track_id="TRK-2025-000941",
        person_name="Unknown Individual #941",
        person_photo="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face",
        status=AlertStatus.ACTIVE,
        guard_notes="Guard unit 2 dispatched to floor 2 server room."
    ),
    SecurityAlert(
        id="alt-102",
        alert_id="ALT-2025-0824-002",
        timestamp="10:21 AM",
        severity=AlertSeverity.HIGH,
        type=AlertType.TAILGATING,
        title="Tailgating Detected - Main Entrance",
        description="Two individuals passed through Turnstile 3 on a single badge scan.",
        building="Corporate Tower A",
        floor="Floor 1",
        room="Main Entrance",
        camera_id="CAM-001",
        status=AlertStatus.INVESTIGATING,
        guard_notes="Front desk reviewing optical sensor playback."
    ),
    SecurityAlert(
        id="alt-103",
        alert_id="ALT-2025-0824-003",
        timestamp="10:18 AM",
        severity=AlertSeverity.HIGH,
        type=AlertType.RESTRICTED_ZONE,
        title="Restricted Area Access - Floor 4",
        description="Contractor TRK-2025-000412 entered Floor 4 Telecom Hub without escort.",
        building="Corporate Tower A",
        floor="Floor 4",
        room="Telecom Hub",
        camera_id="CAM-041",
        status=AlertStatus.RESOLVED,
        guard_notes="Verified escort arrived at 10:20 AM."
    ),
    SecurityAlert(
        id="alt-104",
        alert_id="ALT-2025-0824-004",
        timestamp="10:15 AM",
        severity=AlertSeverity.MEDIUM,
        type=AlertType.UNKNOWN_PERSON,
        title="Unknown Person Detected - Floor 1",
        description="Unregistered visitor loitering near Executive Elevator for > 5 minutes.",
        building="Corporate Tower A",
        floor="Floor 1",
        room="Elevator Lobby",
        camera_id="CAM-007",
        status=AlertStatus.RESOLVED,
        guard_notes="Escorted to Reception for visitor registration."
    )
]

INITIAL_RULES: List[SecurityRule] = [
    SecurityRule(
        id="rule-1",
        name="Restricted Zone Geofencing",
        type=AlertType.UNAUTHORIZED_ACCESS,
        description="Trigger instant critical alarm when any non-whitelisted person enters Server Room or Power Vault",
        is_enabled=True,
        zone_id="room-server",
        severity=AlertSeverity.CRITICAL
    ),
    SecurityRule(
        id="rule-2",
        name="Tailgating / Piggybacking Detection",
        type=AlertType.TAILGATING,
        description="Trigger alert when optical barrier detects multiple occupants per access card swipe (< 1.5s)",
        is_enabled=True,
        threshold_seconds=2,
        severity=AlertSeverity.HIGH
    ),
    SecurityRule(
        id="rule-3",
        name="Corridor Loitering Monitor",
        type=AlertType.LOITERING,
        description="Alert security if any person remains stationary in corridors or staircases > 300 seconds",
        is_enabled=True,
        threshold_seconds=300,
        severity=AlertSeverity.MEDIUM
    ),
    SecurityRule(
        id="rule-4",
        name="Visitor Expiry Enforcement",
        type=AlertType.EXPIRED_PERMISSION,
        description="Alert if a temporary visitor badge remains active within building past expiration time",
        is_enabled=True,
        severity=AlertSeverity.HIGH
    )
]
